name: Test

on:
  push:
    paths-ignore:
      - 'LICENCE'
      - 'LICENSE'
      - '*.md'

    branches:
      - main
      - devel

  pull_request:
    paths-ignore:
      - 'LICENCE'
      - '*.md'

    branches:
      - main
      - devel

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: copy env
        run: cp .env.example .env

      - name: composer install
        run: docker run --rm -u "$(id -u)" -v $(pwd):/src -w /src laravelsail/php81-composer:latest composer i --ignore-platform-reqs

      - name: start mysql
        run: ./vendor/bin/sail up -d mysql

      - name: start
        run: ./vendor/bin/sail up -d

      - name: migrate
        run: ./vendor/bin/sail artisan migrate
      
      - name: test all
        run: ./vendor/bin/sail test

      - name: test Tasks
        run: ./vendor/bin/sail test --filter TasksTest

      - name: test Categories
        run: ./vendor/bin/sail test --filter CategoriesTest
      
      - name: test TaskCategory
        run: ./vendor/bin/sail test --filter TaskCategoryTest